<a href="https://colab.research.google.com/github/jb-612/cursor-analytics-platform/blob/main/dox_dev.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd

file_path = '/content/dev-june/Amdocs_PR_Jun_2026.xlsx'
df = pd.read_excel(file_path)

In [10]:
print('First 5 rows of the DataFrame:')
display(df.head())

print('\nDataFrame information:')
display(df.info())

First 5 rows of the DataFrame:

,repository,number,title,author,state,head_ref,base_ref,created_at,merged_at,closed_at,...,first_review_at,coding_lead_time_hours,pickup_time_hours,review_lead_time_hours,total_cycle_time_hours,iteration_count,changes_requested_count,is_revert,has_review,labels
0,digitalexp-b2b-ui-e2e-test,1524,Mstr/Srushti,user-2fb7b43939c6,MERGED,mstr/Srushti,master,2026-06-01 03:16:51,2026-06-03 06:31:00,NaN,...,2026-06-03 06:30:58,16.81,51.24,0.00,68.05,1,0,0,1,NaN
1,playwright-mcp-agent,652,Playwright mcp core rafi,user-48098dacaee8,MERGED,playwright-mcp-core-rafi,master,2026-06-01 03:26:47,2026-06-01 03:26:59,NaN,...,NaN,0.13,NaN,NaN,0.13,0,0,0,0,NaN
2,playwright-mcp-agent,653,release: v1.0.37,user-48098dacaee8,MERGED,playwright-mcp-core-rafi,master,2026-06-01 03:27:33,2026-06-01 03:27:36,NaN,...,NaN,0.00,NaN,NaN,0.00,0,0,0,0,NaN
3,env-utility,1254,groups.yaml edited online with Bitbucket,user-331cca062855,MERGED,vishayad/groupsyaml-1780284715750,master,2026-06-01 03:33:17,2026-06-01 09:32:49,NaN,...,NaN,0.02,NaN,NaN,6.01,0,0,0,0,NaN
4,digital-exp-b2b-app,42508,New technical component created,user-e4c713338e12,MERGED,B2B-storyDev-DE-418025-3,dev,2026-06-01 03:44:20,2026-06-01 05:18:51,NaN,...,2026-06-01 04:37:23,81.65,0.88,0.69,83.22,3,0,0,1,NaN

DataFrame information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15517 entries, 0 to 15516
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   repository               15517 non-null  object
 1   number                   15517 non-null  int64
 2   title                    15517 non-null  object
 3   author                   15517 non-null  object
 4   state                    15517 non-null  object
 5   head_ref                 15517 non-null  object
 6   base_ref                 15517 non-null  object
 7   created_at               15517 non-null  object
 8   merged_at                14761 non-null  object
 9   closed_at                1999 non-null   object
 10  merge_week               14761 non-null  object
 11  merge_month              14761 non-null  object
 12  commit_count             15517 non-null  int64
 13  review_count             15517 non-null  int64
 14  comment_count            15517 non-null  int64
 15  reviewer_count           15517 non-null  int64
 16  first_commit_at          15514 non-null  object
 17  first_review_at          10954 non-null  object
 18  coding_lead_time_hours   15514 non-null  float64
 19  pickup_time_hours        10954 non-null  float64
 20  review_lead_time_hours   10876 non-null  float64
 21  total_cycle_time_hours   14761 non-null  float64
 22  iteration_count          15517 non-null  int64
 23  changes_requested_count  15517 non-null  int64
 24  is_revert                15517 non-null  int64
 25  has_review               15517 non-null  int64
 26  labels                   0 non-null      float64
dtypes: float64(5), int64(9), object(13)
memory usage: 3.2+ MB

None

## Basic Statistics and Data Cleansing

In [11]:
# Display descriptive statistics for numerical columns
print('\nDescriptive Statistics for Numerical Columns:')
display(df.describe())

Descriptive Statistics for Numerical Columns:

,number,commit_count,review_count,comment_count,reviewer_count,coding_lead_time_hours,pickup_time_hours,review_lead_time_hours,total_cycle_time_hours,iteration_count,changes_requested_count,is_revert,has_review,labels
count,15517.000000,15517.000000,15517.000000,15517.000000,15517.000000,15514.000000,10954.000000,10876.000000,14761.000000,15517.000000,15517.00000,15517.000000,15517.000000,0.0
mean,2135.653412,3.013856,1.022878,2.000387,0.975189,83.801024,23.370991,11.463030,109.098033,1.022556,0.00058,0.004833,0.705935,NaN
std,6237.583200,5.583266,0.898097,0.019661,0.818131,844.115083,59.375649,39.676823,810.266139,0.897854,0.02894,0.069357,0.455636,NaN
min,1.000000,0.000000,0.000000,2.000000,0.000000,-497.200000,0.000000,0.000000,-7.940000,0.000000,0.00000,0.000000,0.000000,NaN
25%,98.000000,1.000000,0.000000,2.000000,0.000000,0.010000,0.120000,0.010000,0.370000,0.000000,0.00000,0.000000,0.000000,NaN
50%,376.000000,1.000000,1.000000,2.000000,1.000000,0.040000,1.010000,0.190000,4.630000,1.000000,0.00000,0.000000,1.000000,NaN
75%,1349.000000,3.000000,1.000000,2.000000,1.000000,3.747500,19.265000,1.970000,69.200000,1.000000,0.00000,0.000000,1.000000,NaN
max,42850.000000,50.000000,8.000000,3.000000,5.000000,67139.360000,656.470000,547.170000,67139.570000,8.000000,2.00000,1.000000,1.000000,NaN

In [12]:
# Check for missing values
print('\nMissing values before cleansing:')
display(df.isnull().sum()[df.isnull().sum() > 0].sort_values(ascending=False))

Missing values before cleansing:

labels                    15517
closed_at                 13518
review_lead_time_hours     4641
first_review_at            4563
pickup_time_hours          4563
merge_week                  756
merged_at                   756
merge_month                 756
total_cycle_time_hours      756
coding_lead_time_hours        3
first_commit_at               3
dtype: int64

### Data Cleansing: Handling Missing Values and Data Types

Based on the `df.info()` output and the missing values check:

1.  **`labels`**: This column is entirely null. It will be dropped.
2.  **Date Columns**: `created_at`, `merged_at`, `closed_at`, `first_commit_at`, `first_review_at` will be converted to datetime objects. Missing values in `merged_at` and `closed_at` might indicate PRs that are still open or not yet closed/merged, so we'll keep them as `NaT` (Not a Time) after conversion.
3.  **Time-related numerical columns**: `coding_lead_time_hours`, `pickup_time_hours`, `review_lead_time_hours`, `total_cycle_time_hours` have missing values. For initial analysis, we'll fill these with 0, assuming that a missing value means no time was spent in that phase (e.g., no review lead time if there was no review). However, depending on the specific analysis, a more sophisticated imputation strategy might be needed.
4.  **`merge_week` and `merge_month`**: Convert to appropriate categorical types or derive from `merged_at` if necessary. For now, we'll keep them as objects but address their nulls.

In [13]:
# Drop the 'labels' column as it's entirely null
if 'labels' in df.columns:
    df = df.drop(columns=['labels'])
    print("Dropped 'labels' column due to all null values.")

# Convert date columns to datetime objects
date_cols = ['created_at', 'merged_at', 'closed_at', 'first_commit_at', 'first_review_at']
for col in date_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')
        print(f"Converted '{col}' to datetime.")

# Fill NaN in time-related numerical columns with 0
time_numerical_cols = [
    'coding_lead_time_hours',
    'pickup_time_hours',
    'review_lead_time_hours',
    'total_cycle_time_hours'
]
for col in time_numerical_cols:
    if col in df.columns:
        df[col] = df[col].fillna(0)
        print(f"Filled NaN in '{col}' with 0.")

# For 'merge_week' and 'merge_month', fill NaNs with a placeholder if they exist (e.g., 'Unknown')
# Or, if merged_at is null, then these should also be null. For now, fill with 'Unknown' for object type.
if 'merge_week' in df.columns:
    df['merge_week'] = df['merge_week'].fillna('Unknown')
    print("Filled NaN in 'merge_week' with 'Unknown'.")
if 'merge_month' in df.columns:
    df['merge_month'] = df['merge_month'].fillna('Unknown')
    print("Filled NaN in 'merge_month' with 'Unknown'.")

# Display missing values after cleansing
print('\nMissing values after cleansing:')
display(df.isnull().sum()[df.isnull().sum() > 0].sort_values(ascending=False))

# Display updated DataFrame information to confirm data types and non-null counts
print('\nDataFrame information after cleansing:')
display(df.info())

Dropped 'labels' column due to all null values.
Converted 'created_at' to datetime.
Converted 'merged_at' to datetime.
Converted 'closed_at' to datetime.
Converted 'first_commit_at' to datetime.
Converted 'first_review_at' to datetime.
Filled NaN in 'coding_lead_time_hours' with 0.
Filled NaN in 'pickup_time_hours' with 0.
Filled NaN in 'review_lead_time_hours' with 0.
Filled NaN in 'total_cycle_time_hours' with 0.
Filled NaN in 'merge_week' with 'Unknown'.
Filled NaN in 'merge_month' with 'Unknown'.

Missing values after cleansing:

closed_at          13518
first_review_at     4563
merged_at            756
first_commit_at        3
dtype: int64

DataFrame information after cleansing:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15517 entries, 0 to 15516
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   repository               15517 non-null  object
 1   number                   15517 non-null  int64
 2   title                    15517 non-null  object
 3   author                   15517 non-null  object
 4   state                    15517 non-null  object
 5   head_ref                 15517 non-null  object
 6   base_ref                 15517 non-null  object
 7   created_at               15517 non-null  datetime64[ns]
 8   merged_at                14761 non-null  datetime64[ns]
 9   closed_at                1999 non-null   datetime64[ns]
 10  merge_week               15517 non-null  object
 11  merge_month              15517 non-null  object
 12  commit_count             15517 non-null  int64
 13  review_count             15517 non-null  int64
 14  comment_count            15517 non-null  int64
 15  reviewer_count           15517 non-null  int64
 16  first_commit_at          15514 non-null  datetime64[ns]
 17  first_review_at          10954 non-null  datetime64[ns]
 18  coding_lead_time_hours   15517 non-null  float64
 19  pickup_time_hours        15517 non-null  float64
 20  review_lead_time_hours   15517 non-null  float64
 21  total_cycle_time_hours   15517 non-null  float64
 22  iteration_count          15517 non-null  int64
 23  changes_requested_count  15517 non-null  int64
 24  is_revert                15517 non-null  int64
 25  has_review               15517 non-null  int64
dtypes: datetime64[ns](5), float64(4), int64(9), object(8)
memory usage: 3.1+ MB

None

In [14]:
# Display the first few rows of the cleaned DataFrame
print('\nFirst 5 rows of the DataFrame after cleansing:')
display(df.head())

First 5 rows of the DataFrame after cleansing:

,repository,number,title,author,state,head_ref,base_ref,created_at,merged_at,closed_at,...,first_commit_at,first_review_at,coding_lead_time_hours,pickup_time_hours,review_lead_time_hours,total_cycle_time_hours,iteration_count,changes_requested_count,is_revert,has_review
0,digitalexp-b2b-ui-e2e-test,1524,Mstr/Srushti,user-2fb7b43939c6,MERGED,mstr/Srushti,master,2026-06-01 03:16:51,2026-06-03 06:31:00,NaT,...,2026-05-31 10:28:14,2026-06-03 06:30:58,16.81,51.24,0.00,68.05,1,0,0,1
1,playwright-mcp-agent,652,Playwright mcp core rafi,user-48098dacaee8,MERGED,playwright-mcp-core-rafi,master,2026-06-01 03:26:47,2026-06-01 03:26:59,NaT,...,2026-06-01 03:19:04,NaT,0.13,0.00,0.00,0.13,0,0,0,0
2,playwright-mcp-agent,653,release: v1.0.37,user-48098dacaee8,MERGED,playwright-mcp-core-rafi,master,2026-06-01 03:27:33,2026-06-01 03:27:36,NaT,...,2026-06-01 03:27:24,NaT,0.00,0.00,0.00,0.00,0,0,0,0
3,env-utility,1254,groups.yaml edited online with Bitbucket,user-331cca062855,MERGED,vishayad/groupsyaml-1780284715750,master,2026-06-01 03:33:17,2026-06-01 09:32:49,NaT,...,2026-06-01 03:32:02,NaT,0.02,0.00,0.00,6.01,0,0,0,0
4,digital-exp-b2b-app,42508,New technical component created,user-e4c713338e12,MERGED,B2B-storyDev-DE-418025-3,dev,2026-06-01 03:44:20,2026-06-01 05:18:51,NaT,...,2026-05-28 18:05:31,2026-06-01 04:37:23,81.65,0.88,0.69,83.22,3,0,0,1

## Filtering for Pure Product Code Projects

To focus on 'pure product code projects' and exclude 'scripting, terraform, helm charts, configuration, and devops infra', we'll filter the `repository` column based on keywords.

In [15]:
# Define keywords for inclusion and exclusion
include_keywords = ['java', 'c\\+\\+', 'cpp', 'c#', 'dotnet', 'product', 'backend', 'frontend'] # Corrected escaping for c++
exclude_keywords = [
    'script', 'terraform', 'helm', 'config', 'configuration',
    'infra', 'infrastructure', 'devops', 'e2e-test', 'playwright',
    'utility', 'tool', 'doc', 'test', 'build', 'pipeline'
]

# Let's define the primary inclusion based on all include_keywords
# This will be more general to capture 'product code' even if the language isn't explicit
language_include_mask = df['repository'].str.contains('|'.join(include_keywords), case=False, na=False)

# Define secondary exclusion for common non-product code types
non_product_exclude_mask = df['repository'].str.contains('|'.join(exclude_keywords), case=False, na=False)

# Filter the DataFrame: include if it matches an inclusion keyword AND does not match an exclusion keyword
filtered_df = df[language_include_mask & ~non_product_exclude_mask]

print(f"Original DataFrame shape: {df.shape}")
print(f"Filtered DataFrame shape (product code only): {filtered_df.shape}")

print('\nFirst 5 rows of the filtered DataFrame:')
display(filtered_df.head())

print('\nFiltered DataFrame information:')
display(filtered_df.info())

Original DataFrame shape: (15517, 26)
Filtered DataFrame shape (product code only): (670, 26)

First 5 rows of the filtered DataFrame:

,repository,number,title,author,state,head_ref,base_ref,created_at,merged_at,closed_at,...,first_commit_at,first_review_at,coding_lead_time_hours,pickup_time_hours,review_lead_time_hours,total_cycle_time_hours,iteration_count,changes_requested_count,is_revert,has_review
10,pod-productoffering-ms,4933,Fix : Also condition for replaceable relationT...,user-0edb69ae32dc,MERGED,RS_Case_1289155-052426_Fix_D75,release/0.75,2026-06-01 04:41:59,2026-06-01 05:30:26,NaT,...,2026-06-01 04:40:28,2026-06-01 05:10:59,0.03,0.48,0.32,0.83,2,0,0,1
18,productaccessor-subdomain,311,CI: move MS-trigger post_step to 'Create and U...,user-daa96bdff4cc,MERGED,feature/move-mstrigger-to-create-upload-image,master,2026-06-01 05:02:59,2026-06-01 06:36:22,NaT,...,2026-06-01 05:00:56,2026-06-01 06:21:07,0.03,1.30,0.25,1.59,1,0,0,1
29,productinventorymanagement-experiencev2-ms,92,Fix Sonar duplication gate failure on master,user-e7a20c8fdea5,MERGED,fix/sonar-quality-gate-master,master,2026-06-01 05:25:13,2026-06-01 05:51:21,NaT,...,2026-06-01 05:24:59,2026-06-01 05:42:54,0.00,0.29,0.14,0.44,2,0,0,1
37,productordertoserviceorder-subdomain,44,pom.xml edited online with Bitbucket,user-60e2749e4803,MERGED,mohiniSubdomain,master,2026-06-01 05:45:55,2026-06-01 06:16:14,NaT,...,2026-06-01 05:45:46,2026-06-01 06:15:53,0.00,0.50,0.01,0.51,2,0,0,1
54,pod-productoffering-ms,4934,added support for replaceOffer relationship,user-1a5989f1baf8,MERGED,feature/replaceOffer_addedSupport,master,2026-06-01 06:02:22,2026-06-04 08:11:07,NaT,...,2026-06-01 06:01:08,2026-06-02 07:03:00,0.02,25.01,49.14,74.17,2,0,0,1

Filtered DataFrame information:
<class 'pandas.core.frame.DataFrame'>
Index: 670 entries, 10 to 15511
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   repository               670 non-null    object
 1   number                   670 non-null    int64
 2   title                    670 non-null    object
 3   author                   670 non-null    object
 4   state                    670 non-null    object
 5   head_ref                 670 non-null    object
 6   base_ref                 670 non-null    object
 7   created_at               670 non-null    datetime64[ns]
 8   merged_at                611 non-null    datetime64[ns]
 9   closed_at                72 non-null     datetime64[ns]
 10  merge_week               670 non-null    object
 11  merge_month              670 non-null    object
 12  commit_count             670 non-null    int64
 13  review_count             670 non-null    int64
 14  comment_count            670 non-null    int64
 15  reviewer_count           670 non-null    int64
 16  first_commit_at          670 non-null    datetime64[ns]
 17  first_review_at          586 non-null    datetime64[ns]
 18  coding_lead_time_hours   670 non-null    float64
 19  pickup_time_hours        670 non-null    float64
 20  review_lead_time_hours   670 non-null    float64
 21  total_cycle_time_hours   670 non-null    float64
 22  iteration_count          670 non-null    int64
 23  changes_requested_count  670 non-null    int64
 24  is_revert                670 non-null    int64
 25  has_review               670 non-null    int64
dtypes: datetime64[ns](5), float64(4), int64(9), object(8)
memory usage: 141.3+ KB

None

## Distribution of Total Cycle Time Hours

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(filtered_df['total_cycle_time_hours'], bins=50, kde=True)
plt.title('Distribution of Total Cycle Time Hours for Product Code PRs')
plt.xlabel('Total Cycle Time Hours')
plt.ylabel('Number of Pull Requests')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()